{{- range $volume := .Values.splunkOperator.volumes }}
{{- if $volume.persistentVolumeClaim }}
{{- if $volume.persistentVolumeClaim.claimName }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name:  {{ $volume.persistentVolumeClaim.claimName }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
{{- end }}
{{- end }}
{{- end }}
